services:
  - type: web
    name: ecommerce-backend
    runtime: docker
    rootDir: back-spring
    healthCheckPath: /swagger.html
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
