# Profil de developpement local
# Base dediee dev
spring.datasource.url=jdbc:postgresql://127.0.0.1:55432/ecommerce_dev_db
spring.datasource.username=${DB_USER:ecommerce_app}
spring.datasource.password=${DB_PASSWORD:ecommerce_app_pwd}

# En dev, schema gere par Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
# Permet d'adopter Flyway sur une base deja initialisee a la main.
spring.flyway.baseline-on-migrate=true
# Migrations schema + donnees de dev uniquement
spring.flyway.locations=classpath:db/migration,classpath:db/migration-dev
